package com.bcv.FinalProject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author home
 */
public class testFormNetbeans extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public testFormNetbeans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        labelWeldProcedure = new javax.swing.JLabel();
        weldProcedure = new javax.swing.JComboBox<>();
        labelStandardWeldingJoint = new javax.swing.JLabel();
        standardWeldingJoint = new javax.swing.JTextField();
        labelTypeWeldingJoint = new javax.swing.JLabel();
        typeWeldingJoint = new javax.swing.JComboBox<>();
        labelWeldingPosition = new javax.swing.JLabel();
        weldingPosition = new javax.swing.JComboBox<>();
        labelLengthWeldJoint = new javax.swing.JLabel();
        sizeLengthWeldJoint = new javax.swing.JSpinner();
        labelResult = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        parameters = new javax.swing.JPanel();
        sizeS = new javax.swing.JSpinner();
        S = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        sizeB = new javax.swing.JSpinner();
        e = new javax.swing.JLabel();
        sizeE = new javax.swing.JSpinner();
        g = new javax.swing.JLabel();
        sizeG = new javax.swing.JSpinner();
        e1 = new javax.swing.JLabel();
        sizeE1 = new javax.swing.JSpinner();
        g1 = new javax.swing.JLabel();
        sizeG1 = new javax.swing.JSpinner();
        c = new javax.swing.JLabel();
        sizeC = new javax.swing.JSpinner();
        r = new javax.swing.JLabel();
        sizeR = new javax.swing.JSpinner();
        alpha = new javax.swing.JLabel();
        sizeAlpha = new javax.swing.JSpinner();
        beta = new javax.swing.JLabel();
        sizeBeta = new javax.swing.JSpinner();
        k = new javax.swing.JLabel();
        sizeK = new javax.swing.JSpinner();
        k1 = new javax.swing.JLabel();
        sizeK1 = new javax.swing.JSpinner();
        h = new javax.swing.JLabel();
        sizeH = new javax.swing.JSpinner();
        TypesWeldingJoint = new javax.swing.JTabbedPane();
        buttJoints = new javax.swing.JTabbedPane();
        GOST5264_C1 = new javax.swing.JLabel();
        GOST5264_C2 = new javax.swing.JLabel();
        GOST5264_C3 = new javax.swing.JLabel();
        GOST5264_C4 = new javax.swing.JLabel();
        GOST5264_C5 = new javax.swing.JLabel();
        GOST5264_C6 = new javax.swing.JLabel();
        GOST5264_C7 = new javax.swing.JLabel();
        GOST5264_C8 = new javax.swing.JLabel();
        GOST5264_C9 = new javax.swing.JLabel();
        GOST5264_C10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("weldering.com");
        setName("mainFrame"); // NOI18N

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Калькулятор расчета сварочных материалов", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelWeldProcedure.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelWeldProcedure.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWeldProcedure.setText("Способ сварки");

        weldProcedure.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weldProcedure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIG", "MIG", "MAG", "MMA", "SAW" }));
        weldProcedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weldProcedureActionPerformed(evt);
            }
        });

        labelStandardWeldingJoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelStandardWeldingJoint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelStandardWeldingJoint.setText("Стандарт на тип сварного соединения");

        standardWeldingJoint.setEditable(false);
        standardWeldingJoint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        standardWeldingJoint.setText("ГОСТ 14771-76");
        standardWeldingJoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardWeldingJointActionPerformed(evt);
            }
        });

        labelTypeWeldingJoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTypeWeldingJoint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTypeWeldingJoint.setText("Тип сварного соединения");

        typeWeldingJoint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeWeldingJoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "стыковое", "угловое", "тавровое", "нахлесточное" }));
        typeWeldingJoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeWeldingJointActionPerformed(evt);
            }
        });

        labelWeldingPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelWeldingPosition.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWeldingPosition.setText("Положение при сварке");

        weldingPosition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weldingPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "нижнее", "вертикальное", "потолочное" }));

        labelLengthWeldJoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelLengthWeldJoint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLengthWeldJoint.setText("Длина сварного шва, cм");

        sizeLengthWeldJoint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeLengthWeldJoint.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        labelResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelResult.setText("Количество сварочных материалов, кг");

        result.setEditable(false);
        result.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        result.setText("0");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        calculate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calculate.setText("Рассчитать количество сварочных материалов, кг");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("Выход");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(labelWeldProcedure)
                                                .addGap(18, 18, 18)
                                                .addComponent(weldProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(labelStandardWeldingJoint)
                                                .addGap(18, 18, 18)
                                                .addComponent(standardWeldingJoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(labelTypeWeldingJoint)
                                                .addGap(18, 18, 18)
                                                .addComponent(typeWeldingJoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelLengthWeldJoint)
                                                        .addComponent(labelWeldingPosition))
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(sizeLengthWeldJoint, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(weldingPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(labelResult)
                                                .addGap(18, 18, 18)
                                                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exit)
                                .addContainerGap())
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelLengthWeldJoint, labelResult, labelStandardWeldingJoint, labelTypeWeldingJoint, labelWeldProcedure, labelWeldingPosition});

        mainPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {result, sizeLengthWeldJoint, standardWeldingJoint, weldProcedure, weldingPosition});

        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelWeldProcedure)
                                        .addComponent(weldProcedure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelStandardWeldingJoint)
                                        .addComponent(standardWeldingJoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTypeWeldingJoint)
                                        .addComponent(typeWeldingJoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelWeldingPosition)
                                        .addComponent(weldingPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelLengthWeldJoint)
                                        .addComponent(sizeLengthWeldJoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(calculate)
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelResult)
                                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(exit)
                                .addGap(29, 29, 29))
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelLengthWeldJoint, labelResult, labelStandardWeldingJoint, labelWeldProcedure, labelWeldingPosition, result, sizeLengthWeldJoint, standardWeldingJoint, weldProcedure, weldingPosition});

        parameters.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        sizeS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeS.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        S.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        S.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        S.setText("S, мм");

        b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        b.setText("b, мм");

        sizeB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        e.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        e.setText("e, мм");

        sizeE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeE.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        g.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        g.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        g.setText("g, мм");

        sizeG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeG.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        e1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        e1.setText("e1, мм");

        sizeE1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeE1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        g1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        g1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        g1.setText("g1, мм");

        sizeG1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeG1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        c.setText("c, мм");

        sizeC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeC.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        r.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        r.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        r.setText("R, мм");

        sizeR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeR.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        alpha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alpha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alpha.setText("α°");

        sizeAlpha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeAlpha.setModel(new javax.swing.SpinnerNumberModel(0, 0, 90, 1));

        beta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        beta.setText("β°");

        sizeBeta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeBeta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 90, 1));

        k.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        k.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        k.setText("K, мм");

        sizeK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeK.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        k1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        k1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        k1.setText("K1, мм");

        sizeK1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeK1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        h.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        h.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        h.setText("h, мм");

        sizeH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sizeH.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout parametersLayout = new javax.swing.GroupLayout(parameters);
        parameters.setLayout(parametersLayout);
        parametersLayout.setHorizontalGroup(
                parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parametersLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(parametersLayout.createSequentialGroup()
                                                .addComponent(k1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sizeK1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(parametersLayout.createSequentialGroup()
                                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                                                        .addComponent(e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(S, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(sizeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(sizeB, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                        .addComponent(sizeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(sizeG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(e1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeE1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(g1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeG1))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeH))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeR))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(alpha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeAlpha))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(beta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeBeta))
                                                        .addGroup(parametersLayout.createSequentialGroup()
                                                                .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sizeK)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        parametersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sizeAlpha, sizeB, sizeBeta, sizeC, sizeE, sizeE1, sizeG, sizeG1, sizeH, sizeK, sizeK1, sizeR, sizeS});

        parametersLayout.setVerticalGroup(
                parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(parametersLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(S)
                                        .addComponent(sizeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b)
                                        .addComponent(sizeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(e)
                                        .addComponent(sizeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g)
                                        .addComponent(sizeG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(e1)
                                        .addComponent(sizeE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g1)
                                        .addComponent(sizeG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(c)
                                        .addComponent(sizeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(h)
                                        .addComponent(sizeH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(r)
                                        .addComponent(sizeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alpha)
                                        .addComponent(sizeAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(beta)
                                        .addComponent(sizeBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(k)
                                        .addComponent(sizeK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(k1)
                                        .addComponent(sizeK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        GOST5264_C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С1.gif"))); // NOI18N
        GOST5264_C1.setToolTipText("");
        GOST5264_C1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                GOST5264_C1ComponentShown(evt);
            }
        });
        buttJoints.addTab("С1", GOST5264_C1);

        GOST5264_C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С2.gif"))); // NOI18N
        buttJoints.addTab("C2", GOST5264_C2);

        GOST5264_C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С3.gif"))); // NOI18N
        buttJoints.addTab("C3", GOST5264_C3);

        GOST5264_C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С4.gif"))); // NOI18N
        GOST5264_C4.setText("jLabel1");
        buttJoints.addTab("C4", GOST5264_C4);

        GOST5264_C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С5.gif"))); // NOI18N
        buttJoints.addTab("C5", GOST5264_C5);

        GOST5264_C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С6.gif"))); // NOI18N
        buttJoints.addTab("C6", GOST5264_C6);

        GOST5264_C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С7.gif"))); // NOI18N
        buttJoints.addTab("C7", GOST5264_C7);

        GOST5264_C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С8.gif"))); // NOI18N
        buttJoints.addTab("C8", GOST5264_C8);

        GOST5264_C9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С9.gif"))); // NOI18N
        buttJoints.addTab("C9", GOST5264_C9);

        GOST5264_C10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weldingcalculator/Images/GOST5264/GOST5264_С10.gif"))); // NOI18N
        GOST5264_C10.setToolTipText("");
        buttJoints.addTab("С10", GOST5264_C10);

        TypesWeldingJoint.addTab("Стыковое", buttJoints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(parameters, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TypesWeldingJoint, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TypesWeldingJoint, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(parameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 5, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void weldProcedureActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void standardWeldingJointActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void typeWeldingJointActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    //button exit from program
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void GOST5264_C1ComponentShown(java.awt.event.ComponentEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testFormNetbeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testFormNetbeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testFormNetbeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testFormNetbeans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testFormNetbeans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel GOST5264_C1;
    private javax.swing.JLabel GOST5264_C10;
    private javax.swing.JLabel GOST5264_C2;
    private javax.swing.JLabel GOST5264_C3;
    private javax.swing.JLabel GOST5264_C4;
    private javax.swing.JLabel GOST5264_C5;
    private javax.swing.JLabel GOST5264_C6;
    private javax.swing.JLabel GOST5264_C7;
    private javax.swing.JLabel GOST5264_C8;
    private javax.swing.JLabel GOST5264_C9;
    private javax.swing.JLabel S;
    private javax.swing.JTabbedPane TypesWeldingJoint;
    private javax.swing.JLabel alpha;
    private javax.swing.JLabel b;
    private javax.swing.JLabel beta;
    private javax.swing.JTabbedPane buttJoints;
    private javax.swing.JLabel c;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel e;
    private javax.swing.JLabel e1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel g;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel h;
    private javax.swing.JLabel k;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel labelLengthWeldJoint;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelStandardWeldingJoint;
    private javax.swing.JLabel labelTypeWeldingJoint;
    private javax.swing.JLabel labelWeldProcedure;
    private javax.swing.JLabel labelWeldingPosition;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel parameters;
    private javax.swing.JLabel r;
    private javax.swing.JTextField result;
    private javax.swing.JSpinner sizeAlpha;
    private javax.swing.JSpinner sizeB;
    private javax.swing.JSpinner sizeBeta;
    private javax.swing.JSpinner sizeC;
    private javax.swing.JSpinner sizeE;
    private javax.swing.JSpinner sizeE1;
    private javax.swing.JSpinner sizeG;
    private javax.swing.JSpinner sizeG1;
    private javax.swing.JSpinner sizeH;
    private javax.swing.JSpinner sizeK;
    private javax.swing.JSpinner sizeK1;
    private javax.swing.JSpinner sizeLengthWeldJoint;
    private javax.swing.JSpinner sizeR;
    private javax.swing.JSpinner sizeS;
    private javax.swing.JTextField standardWeldingJoint;
    private javax.swing.JComboBox<String> typeWeldingJoint;
    private javax.swing.JComboBox<String> weldProcedure;
    private javax.swing.JComboBox<String> weldingPosition;
    // End of variables declaration
}
